openapi: 3.0.0
paths:
  /analytics/daily-summary:
    get:
      tags:
        - Analytics
      summary: Get daily financial summary (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: date
          schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Date in YYYY-MM-DD format (defaults to today)
      responses:
        200:
          description: Daily summary
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DailySummaryResponse"
        401:
          description: Unauthorized
        403:
          description: Forbidden (Admin only)
