openapi: 3.0.0
paths:
  /expenses:
    post:
      tags:
        - Expenses
      summary: Create a new expense (ADMIN only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateExpenseRequest"
      responses:
        201:
          description: Expense created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpenseResponse"
        401:
          description: Unauthorized
        403:
          description: Forbidden (Admin only)
