import { MenuItem, Prisma, StockAdjustment } from "@prisma/client";

export type UserWithProfile = Prisma.UserGetPayload<{
  include: { profile: true };
}>;

// ======== INVENTORY TYPES ===========
/**
 * MenuItem with stock information included
 */
export type MenuItemWithStock = MenuItem & {
  stockAdjustments?: StockAdjustment[];
};

/**
 * Inventory Types (NOT generated by Prisma - custom enum)
 */
export enum InventoryType {
  TRACKED = "TRACKED", // Stock control
  UNLIMITED = "UNLIMITED", // Without limit
}

// =============================
// ORDER TYPES
// =============================

/**
 * Order with all relations included
 *
 * Includes:
 * - items: Array of OrderItem with MenItem details
 * - table: Table information (optional)
 * - waiter: User who took the Order
 * - customer: Customer information (optional)
 * - pauments: Payment records (optional)
 */
export type OrderWithRelations = Prisma.OrderGetPayload<{
  include: {
    items: {
      include: {
        menuItem: true;
      };
    };
    table: true;
    waiter: {
      select: {
        id: true;
        firstName: true;
        lastName: true;
        email: true;
      };
    };
    customer: true;
    payments: true;
  };
}>;

/**
 * Order with items only (most common use case)
 *
 * Used for:
 * - Order creation responses
 * - Order list displays
 * - POST/Mobile interfaces
 */
export type OrderWithItems = Prisma.OrderGetPayload<{
  include: {
    items: {
      include: {
        menuItem: true;
      };
    };
  };
}>;

// Re-export enums from @prisma/client (these are generated by Prisma)
// OrderStatus, OrderItemStatus, OrderType, StockAdjustmentType are defined in schema.prisma
export { OrderStatus, OrderItemStatus, OrderType } from "@prisma/client";
