openapi: 3.0.0
paths:
  /cash-closures/current:
    get:
      tags:
        - Cash Closures
      summary: Get the current open cash closure shift (ADMIN/CASHIER only)
      security:
        - bearerAuth: []
      responses:
        200:
          description: Current open cash closure shift or null
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CashClosureResponse"
        401:
          description: Unauthorized
        403:
          description: Forbidden (Admin or Cashier only)
